import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.setDefaultTimeout(10000);
page.on('pageerror',e=>errors.push(e.message));
try {
await page.goto(base);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/vagyonado-desktop.png',fullPage:false});
console.log('Hero kész');await page.getByRole('button',{name:'Kiszámolom a vagyonadómat'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('1500');
assert.match(await page.getByTestId('live-tax').textContent(),/5\s*000\s*000 Ft/);
await page.getByRole('button',{name:'Részletes eredmény',exact:true}).click();
await page.getByTestId('dialog-final-tax').waitFor({state:'visible'});assert.match(await page.getByTestId('dialog-final-tax').textContent(),/5\s*000\s*000 Ft/);
await page.getByRole('button',{name:'Részletes eredmény bezárása'}).click();
console.log('Számítás kész');await page.getByRole('button',{name:'Levonások megadása',exact:true}).click();
await page.getByRole('spinbutton',{name:'Igazolt, levonható tartozások',exact:true}).fill('100');
await page.getByRole('checkbox',{name:'A tartozás megfelel a tervezet igazolási és levonhatósági feltételeinek'}).check();
await page.getByRole('button',{name:'Eredmény megtekintése',exact:true}).click();assert.match(await page.getByTestId('final-tax').textContent(),/4\s*000\s*000 Ft/);
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Kalkuláció letöltése'}).click();assert.equal((await download).suggestedFilename(),'ICT-Europa-vagyonado-kalkulacio.txt');
await page.getByRole('button',{name:'Adatok módosítása'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('-1');assert.match(await page.getByRole('alert').textContent(),/nem lehetnek negatívak/);assert.equal(await page.getByRole('button',{name:'Levonások megadása',exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'Újrakezdés',exact:true}).click();await page.getByRole('button',{name:'Igen, újrakezdem'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('800');
await page.getByRole('button',{name:'Vagyonelem hozzáadása',exact:true}).click();await page.getByRole('button',{name:'Társasági részesedés',exact:true}).click();
await page.getByRole('spinbutton',{name:'Beszámoló szerinti saját tőke',exact:true}).fill('300');
const profitLabels=['Utolsó lezárt üzleti év','Előző lezárt üzleti év','Az azt megelőző lezárt üzleti év'].map(year=>`${year} adózott eredménye`);
const lastProfit=page.getByRole('spinbutton',{name:profitLabels[0],exact:true});
await lastProfit.fill('');await lastProfit.pressSequentially('-');
assert.equal(await lastProfit.evaluate(input=>input.validity.badInput),true);
assert.equal(await page.getByRole('button',{name:'Levonások megadása',exact:true}).isDisabled(),true);
await lastProfit.pressSequentially('3.2');assert.equal(await lastProfit.inputValue(),'-3.2');
await lastProfit.fill('');await lastProfit.pressSequentially('-0.2');assert.equal(await lastProfit.inputValue(),'-0.2');
await lastProfit.press('Tab');assert.equal(await lastProfit.inputValue(),'-0.2');
const previousProfit=page.getByRole('spinbutton',{name:profitLabels[1],exact:true});
await previousProfit.fill('');await previousProfit.pressSequentially('-8.9');assert.equal(await previousProfit.inputValue(),'-8.9');
await page.getByRole('spinbutton',{name:profitLabels[2],exact:true}).fill('0');
assert.match(await page.locator('.company-answer small').textContent(),/0 M Ft/);
assert.match(await page.locator('.company-answer strong').textContent(),/100 M Ft/);
assert.equal(await page.getByRole('alert').count(),0);
for(const [i,value] of [70,90,110].entries())await page.getByRole('spinbutton',{name:profitLabels[i],exact:true}).fill(String(value));
await page.getByRole('spinbutton',{name:'Tulajdoni hányad',exact:true}).last().fill('60');assert.match(await page.getByTestId('live-tax').textContent(),/1\s*000\s*000 Ft/);
await page.getByRole('spinbutton',{name:'Tulajdoni hányad',exact:true}).last().fill('40');assert.match(await page.getByTestId('live-tax').textContent(),/^0 Ft$/);
console.log('Validáció kész');await page.getByRole('button',{name:'Elolvasom az elemzést'}).click();assert.match(page.url(),/cikkek\/vagyonado-2026/);assert.match(await page.locator('article').textContent(),/101 milliárd Ft/);const source=await page.request.get(base+'/forrasok/vagyonado-cikk-vfinal.docx');assert.equal(source.status(),200);
await page.goBack();await page.reload();
console.log('Cikk kész');await page.getByRole('button',{name:'Beszéljünk a vagyonáról'}).click();
const form=page.locator('.contact-form-card form');await form.locator('[name="lastName"]').fill('Teszt');await form.locator('[name="firstName"]').fill('Minta');await form.locator('[name="email"]').fill('minta@example.com');await form.locator('[name="phone"]').fill('+36 20 123 4567');await page.getByRole('checkbox',{name:'Vállalkozás kapcsán kérek segítséget'}).uncheck();await form.locator('[name="message"]').fill('Ez egy automatikus tesztmegkeresés.');
await form.getByRole('button',{name:'adatkezelési tájékoztatót'}).click();const contactPrivacy=page.getByRole('dialog',{name:'Adatkezelési tájékoztató',exact:true});assert.equal(await contactPrivacy.isVisible(),true);await contactPrivacy.getByRole('button',{name:'Elolvastam',exact:true}).click();await form.locator('[name="consent"]').check();
console.log('Űrlap kész');await form.getByRole('button',{name:'Kérem a konzultációt'}).click();await page.getByText('A tesztmegkeresést rögzítettük.').waitFor();
const api=await page.request.get(base+'/api/health');assert.equal(api.status(),200);
const newsletter=page.getByRole('form',{name:'Hírlevél-feliratkozás'});
assert.equal(await newsletter.getByRole('button',{name:'Feliratkozom!'}).isDisabled(),true);
await newsletter.getByRole('button',{name:'Elolvasom az adatkezelési tájékoztatót'}).click();
const newsletterPrivacy=page.getByRole('dialog',{name:'Adatkezelési tájékoztató (GDPR)',exact:true});
assert.equal(await newsletterPrivacy.isVisible(),true);assert.match(await newsletterPrivacy.textContent(),/ICT Európa Finance Zrt\./);assert.match(await newsletterPrivacy.textContent(),/27035878-2-43/);assert.match(await newsletterPrivacy.textContent(),/72 órán belül/);
await page.keyboard.press('Escape');assert.equal(await newsletterPrivacy.isVisible(),false);
assert.match(await page.locator('.calculation-disclaimer').textContent(),/A felelősségkizárás nem terjed ki/);
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/vagyonado-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobilon vízszintes túlcsordulás');
await page.getByRole('button',{name:'Menü megnyitása'}).click();await page.getByRole('button',{name:'Kalkulátor',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Menü megnyitása'}).getAttribute('aria-expanded'),'false');
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('1500');await page.getByRole('button',{name:'Részletes eredmény',exact:true}).click();await page.getByTestId('dialog-final-tax').waitFor({state:'visible'});assert.match(await page.getByTestId('dialog-final-tax').textContent(),/5\s*000\s*000 Ft/);await page.keyboard.press('Escape');assert.equal(await page.locator('.result-dialog').isVisible(),false);
assert.deepEqual(errors,[]);
} finally { await browser.close(); }
console.log('Böngészőteszt sikeres: számítás, levonás, validáció, letöltés, cikk, űrlap és mobil navigáció.');
