import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {verifyExpertFlow,verifyCompanyGate} from './expert-flow.mjs';
const base=process.env.TEST_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.setDefaultTimeout(10000);
page.on('pageerror',e=>errors.push(e.message));
try {
await page.goto(base);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/vagyonado-desktop.png',fullPage:false});
console.log('Hero kész');await page.getByRole('button',{name:'Kiszámolom a vagyonadómat'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('1500');
assert.match(await page.getByTestId('live-tax').textContent(),/5\s*000\s*000 Ft/);
await page.getByRole('button',{name:'Részletes eredmény',exact:true}).click();
await page.getByTestId('dialog-final-tax').waitFor({state:'visible'});assert.match(await page.getByTestId('dialog-final-tax').textContent(),/5\s*000\s*000 Ft/);
await page.getByRole('button',{name:'Részletes eredmény bezárása'}).click();
console.log('Számítás kész');await page.getByRole('button',{name:'Levonások megadása',exact:true}).click();
await page.getByRole('spinbutton',{name:'Igazolt, levonható tartozások',exact:true}).fill('100');
await page.getByRole('checkbox',{name:'A tartozás megfelel a tervezet igazolási és levonhatósági feltételeinek'}).check();
await page.getByRole('button',{name:'Eredmény megtekintése',exact:true}).click();assert.match(await page.getByTestId('final-tax').textContent(),/4\s*000\s*000 Ft/);
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Kalkuláció letöltése'}).click();const report=await download;assert.equal(report.suggestedFilename(),'ICT-Europa-vagyonado-kalkulacio.txt');assert.match(readFileSync(await report.path(),'utf8'),/alapvagyon-becslés/);assert.match(readFileSync(await report.path(),'utf8'),/egyedi vizsgálat szükséges/);
await page.getByRole('button',{name:'Adatok módosítása'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('-1');assert.match(await page.getByRole('alert').textContent(),/nem lehetnek negatívak/);assert.equal(await page.getByRole('button',{name:'Levonások megadása',exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'Újrakezdés',exact:true}).click();await page.getByRole('button',{name:'Igen, újrakezdem'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('800');
await page.getByRole('button',{name:'Vagyonelem hozzáadása',exact:true}).click();await page.getByRole('button',{name:'Pénzeszköz, bankszámla',exact:true}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).last().fill('300');
assert.match(await page.getByTestId('live-tax').textContent(),/1\s*000\s*000 Ft/);
await page.getByRole('button',{name:'Vagyonelem hozzáadása',exact:true}).click();await page.getByRole('button',{name:'Jármű',exact:true}).click();
const vehicle=page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).last();
await vehicle.fill('10');assert.match(await page.getByTestId('live-tax').textContent(),/1\s*000\s*000 Ft/);
await vehicle.fill('10.001');assert.match(await page.getByTestId('live-tax').textContent(),/1\s*100\s*000 Ft/);
await page.getByRole('button',{name:'Újrakezdés',exact:true}).click();await page.getByRole('button',{name:'Igen, újrakezdem'}).click();
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('1500');
await verifyCompanyGate(page);await verifyExpertFlow(page);
console.log('Validáció kész');await page.getByRole('button',{name:'Elolvasom az elemzést'}).click();assert.match(page.url(),/cikkek\/vagyonado-2026/);assert.match(await page.locator('article').textContent(),/101 milliárd Ft/);const source=await page.request.get(base+'/forrasok/vagyonado-cikk-vfinal.docx');assert.equal(source.status(),200);
await page.goBack();await page.reload();
console.log('Cikk kész');await page.getByRole('button',{name:'Beszéljünk a vagyonáról'}).click();
const form=page.locator('.contact-form-card form');await form.locator('[name="lastName"]').fill('Teszt');await form.locator('[name="firstName"]').fill('Minta');await form.locator('[name="email"]').fill('minta@example.com');await form.locator('[name="phone"]').fill('+36 20 123 4567');await page.getByRole('checkbox',{name:'Vállalkozás kapcsán kérek segítséget'}).uncheck();await form.locator('[name="message"]').fill('Ez egy automatikus tesztmegkeresés.');
await form.getByRole('button',{name:'adatkezelési tájékoztatót'}).click();const contactPrivacy=page.getByRole('dialog',{name:'Adatkezelési tájékoztató',exact:true});assert.equal(await contactPrivacy.isVisible(),true);await contactPrivacy.getByRole('button',{name:'Elolvastam',exact:true}).click();await form.locator('[name="consent"]').check();
await page.getByRole('combobox',{name:'Konzultáció témája',exact:true}).selectOption('family');
const request=page.waitForRequest(r=>r.url().endsWith('/api/contact')&&r.method()==='POST');
console.log('Űrlap kész');await form.getByRole('button',{name:'Kérem a konzultációt'}).click();
const payload=(await request).postDataJSON();assert.match(payload.message,/Konzultáció témája: Családi és vagyonkezelési struktúrák/);assert.doesNotMatch(JSON.stringify(payload),/1500|assets|profits|settings/);await page.getByText('A tesztmegkeresést rögzítettük.').waitFor();
const api=await page.request.get(base+'/api/health');assert.equal(api.status(),200);
const newsletter=page.getByRole('form',{name:'Hírlevél-feliratkozás'});
assert.equal(await newsletter.getByRole('button',{name:'Feliratkozom!'}).isDisabled(),true);
await newsletter.getByRole('button',{name:'Elolvasom az adatkezelési tájékoztatót'}).click();
const newsletterPrivacy=page.getByRole('dialog',{name:'Adatkezelési tájékoztató (GDPR)',exact:true});
assert.equal(await newsletterPrivacy.isVisible(),true);assert.match(await newsletterPrivacy.textContent(),/ICT Európa Finance Zrt\./);assert.match(await newsletterPrivacy.textContent(),/27035878-2-43/);assert.match(await newsletterPrivacy.textContent(),/72 órán belül/);
await page.keyboard.press('Escape');assert.equal(await newsletterPrivacy.isVisible(),false);
assert.match(await page.locator('.calculation-disclaimer').textContent(),/A felelősségkizárás nem terjed ki/);
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/vagyonado-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobilon vízszintes túlcsordulás');
await page.getByRole('button',{name:'Menü megnyitása'}).click();await page.getByRole('button',{name:'Kalkulátor',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Menü megnyitása'}).getAttribute('aria-expanded'),'false');
await page.getByRole('spinbutton',{name:'Teljes vagyonelem számított értéke',exact:true}).fill('1500');await page.getByRole('button',{name:'Részletes eredmény',exact:true}).click();await page.getByTestId('dialog-final-tax').waitFor({state:'visible'});assert.match(await page.getByTestId('dialog-final-tax').textContent(),/5\s*000\s*000 Ft/);await page.keyboard.press('Escape');assert.equal(await page.locator('.result-dialog').isVisible(),false);
await verifyCompanyGate(page);await verifyExpertFlow(page);
assert.deepEqual(errors,[]);
} finally { await browser.close(); }
console.log('Böngészőteszt sikeres: számítás, levonás, validáció, letöltés, cikk, űrlap és mobil navigáció.');
