import {test} from 'node:test';
import assert from 'node:assert/strict';
import {assetValue,calculate,companyValue,defaultSettings,newAsset,taxOnBase,validate} from '../src/tax';
const settings=(p={})=>({...defaultSettings,...p});
const asset=(p={})=>({...newAsset(),...p});
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
for(const [net,base,tax] of [[0,0,0],[999.999,0,0],[1000,0,0],[1500,500,5],[10000,9000,90],[101000,100000,1000],[102000,101000,1015]])test(`nettó vagyon ${net} M: alap ${base}, adó ${tax}`,()=>{const r=calculate([asset({value:net})],settings());near(r.base,base);near(r.tax,tax);});
test('a sávhatár az adóalap 100 milliárdja',()=>{near(taxOnBase(100000),1000);near(taxOnBase(100000.001),1000.000015);});
test('Minta Kft. és tulajdonosi példa',()=>{const a=asset({kind:'company' as const,equity:300,profits:[70,90,110],share:60,totalShare:60});const c=companyValue(a);near(c.yieldValue,600);near(c.total,500);near(c.value,300);const r=calculate([a,asset({value:600}),asset({kind:'cash' as const,value:200})],settings());near(r.net,1100);assert.equal(r.rounded,1000000);});
for(const [share,discount] of [[32.999,0.3],[33,0.25],[40,0.25],[49.999,0.25],[50,0],[60,0]])test(`kisebbségi sáv ${share}%`,()=>{const c=companyValue(asset({kind:'company' as const,equity:300,profits:[70,90,110],share,totalShare:share}));near(c.discount,discount);near(c.value,500*share/100*(1-discount));});
test('közvetett tulajdon kizárja a kisebbségi korrekciót',()=>{near(companyValue(asset({share:40,totalShare:55,equity:300,profits:[70,90,110]})).value,200);});
test('negatív eredményátlag: nulla hozamérték',()=>{const c=companyValue(asset({equity:300,profits:[-70,20,-40]}));near(c.yieldValue,0);near(c.total,100);});
test('holdingnál a korrigált tőke számít',()=>{near(companyValue(asset({holding:true,equity:600,reserves:306,dividends:50,share:100})).value,856);});
test('pontosan 500 M saját tőke: nincs rejtett tartalék hozzáadás',()=>{near(companyValue(asset({equity:500,reserves:100,profits:[0,0,0]})).equity,500);});
test('500 M felett: rejtett tartalék hozzáadása',()=>{near(companyValue(asset({equity:501,reserves:100,profits:[0,0,0]})).equity,601);});
test('induló társaság kedvezménye valóban teljesül',()=>{const c=companyValue(asset({startup:true,equity:300,profits:[10],yearDays:[365]}));assert.equal(c.startupEligible,true);near(c.total,100);});
test('induló társaság: nyereség kizáró feltétel',()=>{assert.equal(companyValue(asset({startup:true,equity:300,profits:[20],yearDays:[365]})).startupEligible,false);});
test('induló társaság: saját tőke kizáró feltétel',()=>{assert.equal(companyValue(asset({startup:true,equity:501,profits:[0],yearDays:[365]})).startupEligible,false);});
test('induló társaság: múltbeli kizárás megmarad',()=>{assert.equal(companyValue(asset({startup:true,startupLost:true,equity:300,profits:[0],yearDays:[365]})).startupEligible,false);});
test('rövid üzleti év évesítése és két elérhető beszámoló',()=>{near(companyValue(asset({equity:300,profits:[45,90],yearDays:[182.5,365]})).yieldValue,600);});
for(const [kind,value,expected] of [['vehicle',10,0],['vehicle',10.001,10.001],['art',3,0],['art',3.001,3.001],['personal',50,0]] as const)test(`ingóság ${kind}, ${value} M`,()=>{near(assetValue(asset({kind,value}),settings()).value,expected);});
test('ingóság értékhatára a teljes tárgyra, tulajdoni hányad előtt',()=>{near(assetValue(asset({kind:'vehicle' as const,value:12,share:50,totalShare:50}),settings()).value,6);});
test('üzleti használatnál a kis értékű ingóság is számít',()=>{near(assetValue(asset({kind:'vehicle' as const,value:8,business:true}),settings()).value,8);});
test('vagyonkezelési adóalany: nincs személyes ingóság mentesség',()=>{near(assetValue(asset({kind:'vehicle' as const,value:8}),settings({subject:'trust' as const})).value,8);});
test('befektetési nemesfém nem ékszermentesség',()=>{near(assetValue(asset({kind:'metal' as const,value:2}),settings()).value,2);});
test('házastársi fél vagyon: csak egyszer felezünk',()=>{near(assetValue(asset({value:1000,share:60,totalShare:60,allocation:'spouseHalf' as const}),settings()).value,300);});
test('gyermek közös felügyelet alatt',()=>{near(assetValue(asset({value:1200,allocation:'childShared' as const}),settings()).value,600);});
test('gyermek öröksége nem a szülő adóalapja',()=>{near(assetValue(asset({value:1200,allocation:'childSeparate' as const}),settings()).value,0);});
test('a vagyonkezelőnél családi kapcsoló nem felez',()=>{near(assetValue(asset({value:1200,allocation:'spouseHalf' as const}),settings({subject:'trust' as const})).value,1200);});
test('kapcsolt konstrukció: csak kiosztott keret',()=>{near(calculate([asset({value:1500})],settings({subject:'trust' as const,linkedTrusts:true,threshold:400})).tax,11);});
test('nem kapcsolt konstrukció: teljes 1 Mrd keret',()=>{near(calculate([asset({value:1500})],settings({subject:'trust' as const,threshold:0})).tax,5);});
test('külföldi adóalany: pénzeszköz nem számít, magyar ingatlan igen',()=>{near(calculate([asset({kind:'cash' as const,value:2000}),asset({value:1500})],settings({resident:false})).gross,1500);});
test('külföldi adóalany: külföldi ingatlan és általános jog nem számít',()=>{near(calculate([asset({value:1500,country:'foreign' as const}),asset({kind:'other' as const,value:2000})],settings({resident:false})).gross,0);});
test('külföldi adóalany: magyar ingatlanhoz kapcsolódó jog számít',()=>{near(assetValue(asset({kind:'propertyRight' as const,value:500}),settings({resident:false})).value,500);});
test('külföldi ingatlanos cég: magyar ingatlanérték, nem svájci képlet',()=>{near(assetValue(asset({kind:'company' as const,country:'foreign' as const,foreignPropertyCompany:true,value:2000,equity:9999,share:40,totalShare:40}),settings({resident:false})).value,800);});
test('egyezmény szerinti teljes kizárás',()=>{near(assetValue(asset({value:1500,country:'foreign' as const,treaty:'exclude' as const}),settings()).value,0);});
test('egyezmény: alapba számító vagyon és külön adólevonás',()=>{const r=calculate([asset({value:1500,country:'foreign' as const,treaty:'progression' as const}),asset({value:1000})],settings());near(r.base,1500);near(r.tax,15);near(r.treatyCredit,5);near(r.payable,10);});
test('tartozást csak feltételek megerősítésével von le',()=>{const a=[asset({value:1500})];near(calculate(a,settings({debt:100})).base,500);near(calculate(a,settings({debt:100,debtConfirmed:true})).base,400);});
test('jóváírás és a díj 2 M plafonja',()=>{const r=calculate([asset({value:1500})],settings({mandatoryFees:10,feesConfirmed:true,localTaxes:1}));near(r.feeCredit,2);near(r.payable,2);});
test('önkéntes szakértői díj nem jóváírható',()=>{near(calculate([asset({value:1500})],settings({mandatoryFees:10})).feeCredit,0);});
test('jóváírásból nem lesz negatív adó',()=>{near(calculate([asset({value:1100})],settings({localTaxes:5})).payable,0);});
test('ezer forintos kerekítés',()=>{assert.equal(calculate([asset({value:1000.15})],settings()).rounded,2000);});
test('ingatlanjogot csak egyszer von le, tulajdoni arány előtt',()=>{const a=asset({value:1000,rights:200,share:50,totalShare:50});near(assetValue(a,settings()).value,400);near(assetValue({...a,rightsAlreadyIncluded:true},settings()).value,500);});
test('opció: a piaci és belső érték közül a magasabb',()=>{near(assetValue(asset({kind:'option' as const,value:10,optionIntrinsic:15}),settings()).value,15);});
test('csak a különleges MRP számít',()=>{const a=asset({kind:'mrp' as const,value:10});near(assetValue(a,settings()).value,0);near(assetValue({...a,specialMrp:true},settings()).value,10);});
test('érvénytelen értékek, tulajdoni arány és napok megállítják a számítást',()=>{assert.ok(validate([asset({value:-1,share:110,yearDays:[0,365,365]})],settings()).length>=3);assert.ok(validate([asset({value:Infinity})],settings()).length>0);assert.ok(validate([],settings({threshold:1001})).length>0);});
test('külföldi cég alternatív tőkésítési rátája',()=>{const a=asset({country:'foreign' as const,capitalizationRate:10,equity:300,profits:[90,90,90]});near(companyValue(a).yieldValue,900);near(companyValue({...a,country:'hu'}).yieldValue,600);assert.ok(validate([{...a,capitalizationRate:0}],settings()).length>0);});
