import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Building2, Check, FileText, Landmark, Menu, Plus, ShieldCheck, Sparkles, X } from 'lucide-react';
import Calculator from './Calculator';
import ContactForm from './ContactForm';
import Newsletter from './Newsletter';
import NewsletterPrivacy from './NewsletterPrivacy';
import { articles } from './articles';

function Brand({light=false}:{light?:boolean}) { return <a className={`brand ${light?'brand-light':''}`} href="/" aria-label="ICT Európa — főoldal"><span className="brand-symbol"><i/><i/><i/></span><span><strong>ICT<span>EURÓPA</span></strong><small>VAGYONTERVEZÉS & ADÓTANÁCSADÁS</small></span></a>; }
function WealthVisual() {return <div className="wealth-visual">
  <img className="hero-office-photo" src="/images/uveg-irodahaz.jpg" width="1441" height="1092" alt="Modern irodaház nagy, átlátszó üvegfelületekkel és világos belső terekkel" fetchPriority="high"/>
  <div className="office-photo-shade" aria-hidden="true"/>
  <div className="visual-bottom"><span>ÁTLÁTHATÓSÁG. BIZTOS ALAPOK.</span><ArrowUpRight size={26}/></div>
  <div className="example-card"><span className="example-icon"><Sparkles size={21}/></span><div><small>PÉLDA · 1,5 MRD FT NETTÓ VAGYON</small><strong>5 000 000 Ft <span>/ év</span></strong></div><ArrowUpRight size={20}/></div>
  </div>;}
const faqs=[
  ['Már hatályos a vagyonadó?','Ez az oldal a feltöltött 2026-os törvénytervezetet dolgozza fel. A bemutatott szabályok és határidők tervezettek. A dokumentumok hivatalos közzétételét és a jogalkotási eljárás aktuális állását nem ellenőriztük önállóan.'],
  ['Az egész vagyonom után kellene adóznom?','A tervezet szerint az adóköteles vagyonelemek számított értékéből a megfelelően igazolt tartozások levonása után fennmaradó nettó vagyon 1 milliárd Ft feletti része lenne az adóalap. Ez az összesített keret egy adóalanyt illet, nem minden vagyonelemet külön. Kapcsolt vagyonkezelési adóalanyoknál a küszöb közös.'],
  ['A saját lakásom és a vállalkozásom is számít?','Nincs általános mentesség a saját lakásra vagy a működő cégben lévő részesedésre. A számított értéket az egyes vagyonelemekre vonatkozó szabályok határozzák meg. A cégrészesedés könyv szerinti értéke és tervezet szerinti értéke eltérhet.'],
  ['Mi a helyzet a házastársam és a gyermekem vagyonával?','A házastársak külön adóalanyok, külön 1 milliárd Ft-os küszöbbel. A közös vagyon megosztását a szerződések és a nyilatkozati szabályok határozzák meg. A kiskorú vagyona főszabály szerint a szülőknél számít; örökség, saját keresmény és az ezek helyébe lépő vagyon esetén a gyermek külön adóalapja az irányadó.'],
  ['Mi történik az itt megadott adataimmal?','A kalkuláció kizárólag a böngészőben fut. A vagyoni adatokat nem továbbítjuk és nem mentjük tartósan; az oldal újratöltése törli őket. A kalkuláció letölthető saját eszközére. A külön kapcsolatfelvételi tesztűrlap csak az ott megadott adatokat küldi a bemutató kiszolgálónak, külön hozzájárulással.'],
  ['Mennyire pontos a kalkuláció?','A kalkulátor a megadott számított értékekből és besorolásokból követi a dokumentált adóalap-, sáv-, kivétel- és jóváírási szabályokat. Nem helyettesíti a hivatalos ingatlanértéket, értékbecslést, illetőség- vagy egyezményvizsgálatot. Speciális esetben kérjen személyre szabott szakértői segítséget.'],
];
export default function App() {
  const initial=()=>location.pathname.startsWith('/cikkek/')?location.pathname.split('/')[2]:null;
  const [articleSlug,setArticleSlug]=useState<string|null>(initial);
  const [menuOpen,setMenuOpen]=useState(false);
  const [privacy,setPrivacy]=useState(false);
  const [newsletterPrivacy,setNewsletterPrivacy]=useState(false);
  const dialogRef=useRef<HTMLDialogElement>(null);
  const article=articles.find(a=>a.slug===articleSlug);
  useEffect(()=>{const update=()=>{setArticleSlug(initial());setMenuOpen(false);};window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);
  useEffect(()=>{document.title=article?`${article.title} | ICT Európa`:'Vagyonadó 2026 — Tisztán látni, időben tervezni | ICT Európa';},[article]);
  useEffect(()=>{if(privacy)dialogRef.current?.showModal();else dialogRef.current?.close();},[privacy]);
  const navigate=(slug:string|null)=>{history.pushState({},'',slug?`/cikkek/${slug}`:'/');setArticleSlug(slug);setMenuOpen(false);window.scrollTo({top:0,behavior:'instant'});};
  const jump=(id:string)=>{if(articleSlug){history.pushState({},'','/#'+id);setArticleSlug(null);setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),50);}else{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});history.replaceState({},'','/#'+id);}setMenuOpen(false);};
  const contact=()=>jump('kapcsolat');
  return <>
    <a className="skip-link" href="#main-content">Ugrás a tartalomhoz</a>
    <header className="site-header"><div className="container header-inner"><div onClick={e=>{if((e.target as HTMLElement).closest('.brand')){e.preventDefault();navigate(null);}}}><Brand/></div><nav aria-label="Fő navigáció" className={menuOpen?'nav-open':''}><button onClick={()=>jump('kalkulator')}>Kalkulátor</button><button onClick={()=>jump('tudastar')}>Tudástár</button><button onClick={()=>jump('gyik')}>Gyakori kérdések</button><button className="nav-contact" onClick={contact}>Beszéljünk a vagyonáról <ArrowUpRight size={16}/></button></nav><button className="menu-button" aria-label={menuOpen?'Menü bezárása':'Menü megnyitása'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></header>
    <main id="main-content">
    {article?<article className="article-page container"><button className="back-link" onClick={()=>{navigate(null);setTimeout(()=>jump('tudastar'),30);}}>← Vissza a tudástárhoz</button><div className="article-meta"><span>{article.category}</span><span>2026-os tervezet</span><span>{article.time} olvasás</span></div><h1>{article.title}</h1><p className="article-lead">{article.intro}</p><div className="article-byline"><span className="author-mark">ICT</span><div><strong>ICT Európa · Szakmai szerkesztőség</strong><span>Elemzés a rendelkezésre bocsátott dokumentumok alapján</span></div>{article.slug==='vagyonado-2026'&&<a className="text-link" href="/forrasok/vagyonado-cikk-vfinal.docx" download>Véglegesített cikk letöltése <FileText size={15}/></a>}</div><div className="article-body">{article.sections.map(s=><section key={s.title}><h2>{s.title}</h2>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{s.formula&&<pre className="formula">{s.formula}</pre>}{s.table&&<div className="table-scroll"><table><thead><tr>{s.table.head.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{s.table.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}</section>)}<div className="article-source"><h3>Források és szerkesztési megjegyzés</h3><p>Feltöltött törvénytervezet, indokolás, tartalmi összefoglaló és hatásvizsgálati lap. Az első cikk a megküldött v1 anyag szerkesztett vfinal változata: javítottuk a sávhatár megfogalmazását, kiegészítettük az induló cégek feltételeit, és helyreállítottuk a számpéldák képleteit. Nem közlünk ellenőrizetlen szerzőnevet vagy hivatalos megjelenési dátumot.</p><a href="/forrasok/vagyonado-tervezet.pdf" className="text-link" target="_blank" rel="noreferrer">A feltöltött normaszöveg megnyitása <ArrowUpRight size={15}/></a></div><div className="article-cta"><h3>Mit jelent mindez az Ön vagyonára?</h3><button className="button button-dark" onClick={()=>jump('kalkulator')}>Kipróbálom a kalkulátort <ArrowRight size={16}/></button><button className="text-link" onClick={contact}>Szakértővel beszélnék <ArrowUpRight size={16}/></button></div></div></article>:<>
      <section className="hero"><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow"><span/>VAGYONADÓ · 2026-OS TÖRVÉNYTERVEZET</p><h1>Tisztán látni.<br/><em>Időben tervezni.</em></h1><p className="hero-description">Megjelent a vagyonadóról szóló törvénytervezet. Ismerje meg, mit jelenthet az Ön vagyona számára, számolja ki a várható adóterhet, és készüljön fel időben az ICT Európa szakértőivel.</p><div className="hero-actions"><button className="button button-dark" onClick={()=>jump('kalkulator')}>Kiszámolom a vagyonadómat <ArrowUpRight size={18}/></button><button className="hero-secondary" onClick={()=>navigate('vagyonado-2026')}>Elolvasom az elemzést <ArrowRight size={15}/></button></div><div className="hero-assurance"><ShieldCheck size={16}/><span>Név nélkül használható. A vagyoni adatai Önnél maradnak.</span></div></div><WealthVisual/></div><div className="container hero-stats"><div><span className="stat-index">01</span><div><strong>1 milliárd Ft</strong><p><b>Tervezett</b> adómentes nettóvagyon-küszöb</p></div></div><div><span className="stat-index">02</span><div><strong>1% <span>/</span> 1,5%</strong><p><b>Tervezett</b> adómérték a vonatkozó vagyonrészekre</p></div></div><div><span className="stat-index">03</span><div><strong>2026. december 31.</strong><p>Az első <b>tervezett</b> vagyonállapot napja</p></div></div></div></section>
      <div className="draft-strip"><div className="container"><FileText size={17}/><p><strong>Jelenleg társadalmi egyeztetés alatt</strong><span>Az alábbi kalkuláció a 2026. október 6-án ismert törvénytervezet alapján készült. A szabályok a jogalkotási folyamat során változhatnak.</span></p><button onClick={()=>jump('tudastar')}>Ismerje meg a részleteket <ArrowDown size={15}/></button></div></div>
      <Calculator onContact={contact}/>
      <section className="approach-section"><div className="container approach-layout"><div><p className="eyebrow"><span/>ICT EURÓPA · SZAKÉRTŐI SZEMLÉLET</p><h2>A jó döntéshez<br/><em>teljes kép kell.</em></h2><p><strong>A vagyonadó hatása nem áll meg egy számításnál.</strong><br/>Az ingatlanok, a befektetések, a vállalkozói részesedések, a családi vagyon és az alkalmazott vagyonkezelési struktúrák együtt adják a teljes képet. Mi ezeket együtt vizsgáljuk.</p><button className="text-link" onClick={contact}>Gondolkodjunk együtt <ArrowUpRight size={17}/></button></div><div className="approach-items">{[[Landmark,'A teljes adózási kép','Vagyon, levonható kötelezettségek, illetőség és adóalap egy rendszerben.'],[Building2,'Vagyon- és struktúratervezés','Családi vagyon, vállalkozás és vagyonkezelési megoldások összehangolása.'],[ShieldCheck,'Vállalkozói vagyon értékelése','A cégrészesedések értékének és vagyonadó-hatásának szakértői vizsgálata.']].map(([Icon,title,text],i)=>{const I=Icon as typeof Landmark;return <div key={i}><span className="approach-icon"><I size={23} strokeWidth={1.4}/></span><div><h3>{String(title)}</h3><p>{String(text)}</p></div><span className="approach-index">0{i+1}</span></div>;})}</div></div></section>
      <section id="tudastar" className="articles-section section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span/>TUDÁSTÁR</p><h2>Ami a számok<br/><em>mögött van.</em></h2></div><p>Érthető szakmai elemzések.<br/>Hogy a következő döntése már felkészült döntés legyen.</p></div><div className="article-cards">{articles.map((a,i)=><button className={`article-card article-card-${i}`} key={a.slug} onClick={()=>navigate(a.slug)}><div className="article-art"><span className="art-label">ICT / INSIGHT</span>{i===0?<div className="art-document"><FileText size={40} strokeWidth={1}/><i/><i/><i/><span>2026</span></div>:i===1?<div className="art-chart"><i/><i/><i/><span>ST + 2H</span></div>:<div className="art-circles"><i/><i/><i/></div>}<span className="art-arrow"><ArrowUpRight size={23}/></span></div><div className="article-card-body"><div className="card-meta"><span>{a.category}</span><span>{a.time}</span></div><h3>{a.title}</h3><p>{a.intro}</p><span className="read-link">Elolvasom <ArrowRight size={16}/></span></div></button>)}</div></div></section>
      <section id="gyik" className="faq-section section-pad"><div className="container faq-layout"><div><p className="eyebrow"><span/>GYAKORI KÉRDÉSEK</p><h2>Kérdése van?<br/><em>Jó helyen jár.</em></h2><p>Az első válaszok itt vannak.<br/>A személyre szabottakért beszéljünk.</p><button className="text-link" onClick={contact}>Kérdezem a szakértőt <ArrowUpRight size={16}/></button></div><div className="faq-items">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></div></section>
    </>}
      <section id="kapcsolat" className="contact-section section-pad"><div className="container contact-layout"><div className="contact-copy"><p className="eyebrow"><span/>A KÖVETKEZŐ LÉPÉS</p><h2>A vagyona egyedi.<br/><em>A terve is legyen az.</em></h2><p>Egy kalkuláció jó kezdet. Egy átgondolt vagyonterv ennél többet ad: összefüggéseket, lehetőségeket és biztosabb döntéseket.</p><div className="contact-checks"><p><Check size={17}/>Személyre szabott adózási áttekintés</p><p><Check size={17}/>Családi és vállalkozói vagyontervezés</p><p><Check size={17}/>Jogi, számviteli és értékelési szempontok</p></div><div className="contact-signature"><span>ICT</span><div>EURÓPA<strong>Szakértelem a döntései mögött.</strong></div></div><a href="https://icteuropa.hu/" target="_blank" rel="noreferrer" className="text-link">Ismerje meg az ICT Európát <ArrowUpRight size={16}/></a></div><ContactForm onPrivacy={()=>setPrivacy(true)}/></div></section>
      <Newsletter onPrivacy={()=>setNewsletterPrivacy(true)}/>
    </main>
    <footer className="site-footer"><div className="container"><div className="footer-top"><Brand light/><p>Tudatos vagyon. Megalapozott döntések.</p><button className="text-link" onClick={()=>jump('kalkulator')}>Vissza a kalkulátorhoz <ArrowUpRight size={16}/></button></div><section className="calculation-disclaimer" aria-labelledby="disclaimer-title"><h2 id="disclaimer-title">Tájékoztató kalkuláció és felelősségkorlátozás</h2><p>A megjelenített összeg a felhasználó által megadott adatok és a kalkulátorban ismertetett feltételezések alapján készült becslés.</p><p>A kalkuláció a bemutatott adójavaslat feltételezéseit modellezi. A kiszámított összeg tájékoztató becslés, nem pedig fennálló adófizetési kötelezettség megállapítása.</p><p>A kalkulátor és annak eredménye nem minősül jogi vagy adótanácsadásnak, hatósági állásfoglalásnak, és nem helyettesíti az egyedi körülmények szakértői vizsgálatát. Az üzemeltető nem garantálja, hogy a becslés megfelel a felhasználó tényleges vagy később megállapított adókötelezettségének.</p><p>Az üzemeltető a jogszabályok által megengedett körben kizárja felelősségét a kalkuláció eredményére alapított döntésekből eredő károkért. A felelősségkizárás nem terjed ki azokra az esetekre, amelyekben a felelősség kizárását jogszabály tiltja.</p><p>Döntés vagy bevallás előtt ellenőrizni kell a bevitt adatok helyességét, az alkalmazandó szabályokat és a felhasználó egyedi körülményeit.</p></section><div className="footer-sources"><span>Feltöltött források:</span><a href="/forrasok/vagyonado-tervezet.pdf" target="_blank" rel="noreferrer">Törvénytervezet ↗</a><a href="/forrasok/indokolas.pdf" target="_blank" rel="noreferrer">Indokolás ↗</a><a href="/forrasok/tartalmi-osszefoglalo.pdf" target="_blank" rel="noreferrer">Összefoglaló ↗</a><a href="/forrasok/hatasvizsgalat.pdf" target="_blank" rel="noreferrer">Hatásvizsgálat ↗</a></div><div className="footer-bottom"><span>© 2026 ICT Európa · Vagyonadó</span><button onClick={()=>setPrivacy(true)}>Adatkezelési tájékoztató</button><a href="https://icteuropa.hu/" target="_blank" rel="noreferrer">icteuropa.hu <ArrowUpRight size={13}/></a></div></div></footer>
    <NewsletterPrivacy open={newsletterPrivacy} onClose={()=>setNewsletterPrivacy(false)}/>
    <dialog ref={dialogRef} aria-labelledby="contact-privacy-title" onCancel={()=>setPrivacy(false)} onClick={e=>{if(e.target===dialogRef.current)setPrivacy(false);}} className="privacy-dialog"><button className="dialog-close icon-button" onClick={()=>setPrivacy(false)} aria-label="Tájékoztató bezárása"><X/></button><p className="eyebrow">BEMUTATÓ KÖRNYEZET · V1</p><h2 id="contact-privacy-title">Adatkezelési tájékoztató</h2><p>Ez a tájékoztató a helyi bemutató űrlap tesztelésére vonatkozik. Kérjük, csak mintadatokat használjon. A bemutató nem továbbít megkeresést az ICT Európának. Valós kapcsolatfelvételhez használja az ICT Európa hivatalos honlapját.</p><h3>Kalkulátor</h3><p>A vagyoni adatokat kizárólag a böngésző memóriájában dolgozzuk fel. Nem kerülnek a kiszolgálóra, tartós böngészőtárba vagy a kapcsolatfelvételi űrlapba. Az oldal újratöltése törli őket. Nincs követőkód, analitika vagy nem szükséges süti.</p><h3>Tesztűrlap</h3><p>A megadott név, e-mail, opcionális telefonszám, céges mezők és üzenet a bemutató kiszolgáló védett adatbázisába kerül, a hozzájárulás időpontjával és e tájékoztató verziójával. A cél az űrlap működésének ellenőrzése; a jogalap az Ön hozzájárulása. A tesztadatok legfeljebb 30 napig maradnak meg, a kiszolgáló következő takarításakor törlődnek. Nem továbbítjuk őket harmadik félnek.</p><h3>Hozzáférés és törlés</h3><p>A bemutató környezet üzemeltetője fér hozzá a tesztadatokhoz. Hozzáférést vagy törlést az üzemeltetőtől kérhet, a rögzítéskor kapott hivatkozással. Az élesítés előtt a pontos adatkezelőt, elérhetőségeit, adatfeldolgozóit és a valós konzultációs adatkezelés feltételeit rögzítő tájékoztatót jóvá kell hagyni.</p><button className="button button-dark" onClick={()=>setPrivacy(false)}>Elolvastam</button></dialog>
  </>;
}
