import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Plus, Trash2, ChevronDown, ChevronUp, ShieldCheck, Info, Download, RotateCcw, Check, Building2, Landmark, Wallet, Gem, CarFront, CircleHelp, ArrowUpRight, X } from 'lucide-react';
import { assetKinds, calculate, companyValue, defaultSettings, formatFt, formatMillion, newAsset, validate } from './tax';
import type { Asset, AssetKind, Settings } from './tax';

function Money({ label, value, onChange, hint, signed=false }: {label:string;value:number;onChange:(n:number)=>void;hint?:string;signed?:boolean}) {
  const [draft,setDraft]=useState(()=>Number.isNaN(value)?'':String(value));
  const editing=useRef(false);
  useEffect(()=>{if(!editing.current)setDraft(Number.isNaN(value)?'':String(value));},[value]);
  // Keep the browser's intermediate minus sign and decimal point while typing.
  // Native input events also report incomplete values skipped by React's change event.
  return <label className="field"><span>{label}</span><div className="money-input"><input aria-label={label} type="number" min={signed?undefined:0} step="any" value={draft} onFocus={()=>{editing.current=true;}} onBlur={()=>{editing.current=false;if(Number.isFinite(value))setDraft(String(value));}} onInput={e=>{setDraft(e.currentTarget.value);onChange(e.currentTarget.validity.badInput?NaN:Number(e.currentTarget.value));}}/><span>M Ft</span></div>{hint&&<small>{hint}</small>}</label>;
}
const businessYears=['Utolsó lezárt üzleti év','Előző lezárt üzleti év','Az azt megelőző lezárt üzleti év'];
function Toggle({label, checked, onChange, hint}:{label:string;checked:boolean;onChange:(v:boolean)=>void;hint?:string}) {
  return <label className="check-field"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}{hint&&<small>{hint}</small>}</span></label>;
}
const assetIcon = (kind: AssetKind) => kind==='property'||kind==='propertyRight'? Building2 : kind==='company'?Landmark:kind==='vehicle'?CarFront:kind==='art'||kind==='metal'?Gem:Wallet;

function AssetEditor({asset:a, index, settings, onChange, onRemove}:{asset:Asset;index:number;settings:Settings;onChange:(a:Asset)=>void;onRemove:()=>void}) {
  const [open,setOpen]=useState(true);
  const patch=(p:Partial<Asset>)=>onChange({...a,...p});
  const kind=assetKinds.find(k=>k.value===a.kind)!;
  const Icon=assetIcon(a.kind);
  const company=companyValue(a);
  return <div className="asset-card">
    <div className="asset-top"><button type="button" className="asset-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><span className="asset-icon"><Icon size={19}/></span><strong>{a.name||kind.label}</strong><span className="asset-number">{String(index+1).padStart(2,'0')}</span>{open?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button><button type="button" className="icon-button" onClick={onRemove} aria-label={`${index+1}. vagyonelem törlése`}><Trash2 size={16}/></button></div>
    {open&&<div className="asset-body">
      <div className="field-grid"><label className="field"><span>Vagyonelem típusa</span><select value={a.kind} onChange={e=>patch({kind:e.target.value as AssetKind})}>{assetKinds.map(k=><option key={k.value} value={k.value}>{k.label}</option>)}</select></label><label className="field"><span>Megnevezés <em>opcionális</em></span><input value={a.name} maxLength={100} onChange={e=>patch({name:e.target.value})} placeholder="Pl. budapesti lakás"/></label></div>
      {a.kind==='company'&&<label className="field"><span>Értékelés módja</span><select value={a.companyMethod} onChange={e=>patch({companyMethod:e.target.value as Asset['companyMethod']})}><option value="formula">Saját tőke + hozamérték (svájci formula)</option><option value="expert">Már meghatározott szakértői / tőzsdei érték</option><option value="transaction">Igazolt tranzakciós érték (1 éven belül)</option></select></label>}
      {a.kind==='company'&&a.companyMethod==='formula'&&!(a.foreignPropertyCompany&&!settings.resident&&a.country==='foreign')?<>
        <Money label="Beszámoló szerinti saját tőke" value={a.equity} onChange={equity=>patch({equity})} signed/>
        <div className="company-years"><label className="field"><span>Lezárt üzleti évek száma</span><select value={a.profits.length} onChange={e=>{const n=Number(e.target.value);patch({profits:Array.from({length:n},(_,i)=>a.profits[i]??0),yearDays:Array.from({length:n},(_,i)=>a.yearDays[i]??365)});}}><option value={1}>1 év</option><option value={2}>2 év</option><option value={3}>3 év</option></select></label><p>Az adóbevalláskor rendelkezésre álló utolsó beszámolók adatai.</p></div>
        <div className="profit-grid">{a.profits.map((p,i)=><Money key={i} label={`${businessYears[i]} adózott eredménye`} value={p} onChange={v=>patch({profits:a.profits.map((x,j)=>i===j?v:x)})} signed/>)}</div>
        <div className="field-grid"><Money label="Rejtett tartalék, halasztott adó után" value={a.reserves} onChange={reserves=>patch({reserves})} hint="500 M Ft feletti saját tőkénél; könyvvizsgáló által felülvizsgált összeg."/><Money label="Tőkében még szereplő osztalék" value={a.dividends} onChange={dividends=>patch({dividends})} hint="Mérlegfordulónap után jóváhagyott vagy kifizetett összeg."/></div>
        <Toggle label="Holdingvállalkozás" checked={a.holding} onChange={holding=>patch({holding})} hint="A részesedések értéke legalább az egyedi mérleg eszközeinek 90%-a."/>
        {!a.holding&&<><Toggle label="Jogelőd nélkül alapított cég, az első három üzleti évben" checked={a.startup} onChange={startup=>patch({startup})}/>{a.startup&&<Toggle label="Korábbi évben már kizáró feltétel következett be" checked={a.startupLost} onChange={startupLost=>patch({startupLost})} hint="Saját tőke > 500 M Ft vagy hozamérték > saját tőke 25%-a."/>}</>}
        <div className="company-answer"><span>Teljes képlet szerinti cégérték</span><strong>{Number.isFinite(company.total)?formatMillion(company.total):'—'}</strong><small>Hozamérték: {Number.isFinite(company.yieldValue)?formatMillion(company.yieldValue):'—'} · {company.startupEligible&&!a.holding?'Induló kedvezmény alkalmazva':a.holding?'Holdingértékelés':'Általános értékelés'}</small></div>
      </>:<Money label={a.kind==='company'&&a.foreignPropertyCompany&&!settings.resident&&a.country==='foreign'?'A társaság magyar ingatlanainak teljes számított értéke':a.kind==='company'?'Teljes társaság meghatározott értéke':'Teljes vagyonelem számított értéke'} value={a.value} onChange={value=>patch({value})} hint="1 M Ft = 1 000 000 forint. A tulajdoni arányt külön adjuk hozzá."/>}
      <div className="field-grid"><label className="field"><span>Tulajdoni hányad</span><div className="money-input"><input type="number" min="0.001" max="100" step="any" aria-label="Tulajdoni hányad" value={a.share} onChange={e=>{const v=Number(e.target.value);patch({share:v,totalShare:a.totalShare===a.share?v:Math.max(v,a.totalShare)});}}/><span>%</span></div></label><label className="field"><span>{a.kind==='company'?'A társaság bejegyzésének helye':'A vagyonelem helye'}</span><select value={a.country} onChange={e=>patch({country:e.target.value as Asset['country']})}><option value="hu">Magyarország</option><option value="foreign">Külföld</option></select></label></div>
      {a.kind==='company'&&a.companyMethod==='formula'&&<><Toggle label="Kisebbségi korrekció alkalmazása" checked={a.minority} onChange={minority=>patch({minority})}/>{a.minority&&<label className="field"><span>Összes közvetlen és közvetett tulajdoni hányad (%)</span><input type="number" min={a.share} max="100" step="any" value={a.totalShare} onChange={e=>patch({totalShare:Number(e.target.value)})}/><small>50% alatt: 33%-tól 25%, 33% alatt 30% korrekció. Nem jár a szakértői vagy tranzakciós értékre automatikusan.</small></label>}</>}
      {a.kind==='company'&&a.country==='foreign'&&!settings.resident&&<Toggle label="Belföldi ingatlanvagyonnal rendelkező külföldi társaság" checked={a.foreignPropertyCompany} onChange={foreignPropertyCompany=>patch({foreignPropertyCompany})} hint="A törvényi minősítést külön ellenőrizni kell. A 12. § (9) szerinti magyar ingatlanértéket adja meg; a képlet helyett ezt használjuk."/>}
      <div className="asset-hint"><Info size={15}/><p>{kind.hint} <span>{kind.ref}</span></p></div>
      <details className="asset-details"><summary>Kivételszabályok és további beállítások <Plus size={14}/></summary><div className="details-content">
        {settings.subject==='person'&&<label className="field"><span>Családi besorolás</span><select value={a.allocation} onChange={e=>patch({allocation:e.target.value as Asset['allocation']})}><option value="own">Saját / szerződés szerint ide rendelt vagyon</option><option value="spouseHalf">Házastársi közös vagyon: 50–50% megosztás</option><option value="childShared">Gyermek vagyona: közös szülői felügyelet (50%)</option><option value="childSole">Gyermek vagyona: kizárólagos felügyelet (100%)</option><option value="childSeparate">Gyermek öröksége / saját keresménye: külön adóalap</option></select><small>A teljes tételt adja meg: a kiválasztott 50%-ot a tulajdoni hányad után alkalmazzuk. A házastársi besorolást a szerződések és az előírt nyilatkozat alapján válassza ki. A gyermek külön adóalapját külön kalkulációban számítsa.</small></label>}
        {['vehicle','art','personal'].includes(a.kind)&&<Toggle label="Egyéni vállalkozói / őstermelői használat vagy költségelszámolás" checked={a.business} onChange={business=>patch({business})} hint="Ilyenkor a teljes érték számít, értékhatártól függetlenül."/>}
        {a.kind==='mrp'&&<Toggle label="Különleges munkavállalói résztulajdonosi program" checked={a.specialMrp} onChange={specialMrp=>patch({specialMrp})}/>}
        {a.kind==='property'&&<><Money label="Terhelő jogok együttes számított értéke" value={a.rights} onChange={rights=>patch({rights})} hint="A 22. § / Itv. 72. § szerint előzetesen meghatározott összeg, legfeljebb az ingatlan teljes értéke."/><Toggle label="A megadott ingatlanérték már figyelembe veszi a terhelő jogot" checked={a.rightsAlreadyIncluded} onChange={rightsAlreadyIncluded=>patch({rightsAlreadyIncluded})} hint="Ebben az esetben nem vonjuk le még egyszer."/></>}
        {a.kind==='option'&&<Money label="A 23. § szerint számított belső érték" value={a.optionIntrinsic} onChange={optionIntrinsic=>patch({optionIntrinsic})}/>}
        {settings.resident&&a.country==='foreign'&&<label className="field"><span>Alkalmazandó vagyonadó-egyezmény</span><select value={a.treaty} onChange={e=>patch({treaty:e.target.value as Asset['treaty']})}><option value="none">Nincs igazolt eltérő egyezményes rendelkezés</option><option value="exclude">Nem vehető figyelembe — 8. § (3)</option><option value="progression">Figyelembe vehető, külön adólevonás — 8. § (2)</option></select><small>Csak a vagyonadóra kiterjedő egyezmény szakértő által ellenőrzött rendelkezése alapján válasszon. Nem általános külföldi adóbeszámítás.</small></label>}
        {a.kind==='company'&&a.companyMethod==='formula'&&<div>{a.country==='foreign'&&<label className="field"><span>Tőkésítési ráta (%)</span><input type="number" min="0.001" max="100" step="any" value={a.capitalizationRate} onChange={e=>patch({capitalizationRate:Number(e.target.value)})}/><small>Főszabály: 15%. Külföldi cégnél az ország kockázatmentes kamatlába és a nem jegyzett társaság kockázati felára alapján is meghatározható — 1. melléklet VI. Csak szakértővel igazolt alternatív rátát adjon meg.</small></label>}<p className="mini-title">Üzleti évek hosszának korrekciója</p><div className="profit-grid">{a.yearDays.map((d,i)=><label className="field" key={i}><span>{businessYears[i]} napjai</span><input type="number" min={1} value={d} onChange={e=>patch({yearDays:a.yearDays.map((x,j)=>i===j?Number(e.target.value):x)})}/></label>)}</div><p className="small-note">A nem 365 napos év adózott eredményét automatikusan évesítjük.</p></div>}
      </div></details>
    </div>}
  </div>;
}

export default function Calculator({onContact}:{onContact:()=>void}) {
  const [assets,setAssets]=useState<Asset[]>([newAsset()]);
  const [settings,setSettings]=useState<Settings>({...defaultSettings});
  const [step,setStep]=useState(0);
  const [addOpen,setAddOpen]=useState(false);
  const [resetOpen,setResetOpen]=useState(false);
  const [detailsOpen,setDetailsOpen]=useState(false);
  const resultDialog=useRef<HTMLDialogElement>(null);
  const scrollPending=useRef(false);
  useEffect(()=>{
    if(!scrollPending.current)return;
    scrollPending.current=false;
    document.getElementById('calculator-tabs')?.scrollIntoView({block:'start',behavior:'smooth'});
  },[step]);
  useEffect(()=>{
    const dialog=resultDialog.current;
    if(!detailsOpen){dialog?.close();return;}
    dialog?.showModal();
    if(dialog){dialog.scrollTop=0;dialog.querySelector<HTMLElement>('h3')?.focus({preventScroll:true});}
    const previousOverflow=document.body.style.overflow;
    document.body.style.overflow='hidden';
    return()=>{document.body.style.overflow=previousOverflow;};
  },[detailsOpen]);
  const errors=validate(assets,settings);
  const result=calculate(assets,settings);
  const patch=(s:Partial<Settings>)=>setSettings({...settings,...s});
  const hasValue=assets.some(a=>a.value>0||a.equity!==0||a.profits.some(p=>p!==0));
  const steps=['Vagyonelemek','Levonások','Eredmény'];
  const move=(n:number)=>{
    if(n===step){document.getElementById('calculator-tabs')?.scrollIntoView({block:'start',behavior:'smooth'});return;}
    scrollPending.current=true;setStep(n);
  };
  const exportReport=()=>{
    const lines=['ICT Európa — Vagyonadó-kalkuláció','A feltöltött 2026-os törvénytervezet alapján. Tájékoztató becslés, nem adóbevallás.','Összegek forintban.',`Adóalany: ${settings.subject==='person'?'magánszemély':'vagyonkezelési adóalany'}; illetőség: ${settings.resident?'belföldi':'külföldi'}`,'',...result.items.map(i=>`${i.asset.name||assetKinds.find(k=>k.value===i.asset.kind)?.label}: ${formatFt(i.value*1e6)} (${i.asset.share}% tulajdon)\n${i.reasons.join(' ')}`),'',`Adóköteles vagyon: ${formatFt(result.gross*1e6)}`,`Igazolt tartozás: ${formatFt(result.debt*1e6)}`,`Nettó vagyon: ${formatFt(result.net*1e6)}`,`Alkalmazott küszöb: ${formatFt(result.threshold*1e6)}`,`Adóalap: ${formatFt(result.base*1e6)}`,`Számított adó: ${formatFt(result.tax*1e6)}`,`Szakértői díj jóváírása: ${formatFt(result.feeCredit*1e6)}`,`Helyi / járműadó jóváírása: ${formatFt(settings.localTaxes*1e6)}`,`Egyezményes adólevonás: ${formatFt(result.treatyCredit*1e6)}`,`Becsült éves adó, ezer Ft-ra kerekítve: ${formatFt(result.rounded)}`,'','Szabályok: 6–9. §; 12. §; 22–25. §; 1. melléklet. A vagyonelemek helyes értékelése és jogi minősítése külön ellenőrzést igényel.'];
    const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));
    const link=document.createElement('a');link.href=url;link.download='ICT-Europa-vagyonado-kalkulacio.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  const renderResult=(isDialog=false)=><>
        <div className="panel-title"><div><h3 id={isDialog?'result-dialog-title':undefined} tabIndex={isDialog?-1:undefined}>Így áll össze a becslése.</h3><p>Egy adóalany tervezet szerinti, éves kalkulációja.</p></div><span className="tiny-pill">Részletes levezetés</span></div>
        {errors.length>0?<div className="empty-state"><CircleHelp size={32}/><h4>Javítsa a megadott adatokat.</h4><p>Érvényes összegek és arányok után megjelenik a részletes becslés.</p><button type="button" className="button button-dark" onClick={()=>{setDetailsOpen(false);move(0);}}>Adatok ellenőrzése <ArrowRight size={16}/></button></div>:!hasValue?<div className="empty-state"><CircleHelp size={32}/><h4>Még nem adott meg vagyoni értéket.</h4><p>Adjon hozzá egy vagyonelemet a személyre szabott becsléshez.</p><button type="button" className="button button-dark" onClick={()=>{setDetailsOpen(false);move(0);}}>Vagyonelemek megadása <ArrowRight size={16}/></button></div>:<>
          <div className="result-lines">{result.items.map(i=><div key={i.asset.id}><div><span>{i.asset.name||assetKinds.find(k=>k.value===i.asset.kind)?.label}</span><strong>{formatFt(i.value*1e6)}</strong></div>{i.reasons.map((r,j)=><small key={j}>{r}</small>)}</div>)}</div>
          <dl className="breakdown"><div><dt>Adóköteles vagyon összesen</dt><dd>{formatFt(result.gross*1e6)}</dd></div><div><dt>Igazolt tartozások</dt><dd>− {formatFt(result.debt*1e6)}</dd></div><div className="strong"><dt>Nettó vagyon</dt><dd>{formatFt(result.net*1e6)}</dd></div><div><dt>Alkalmazott adómentes küszöb</dt><dd>− {formatFt(result.threshold*1e6)}</dd></div><div className="strong"><dt>Adóalap</dt><dd>{formatFt(result.base*1e6)}</dd></div><div><dt>1%-os sáv adója</dt><dd>{formatFt(Math.min(result.base,100000)*10000)}</dd></div><div><dt>1,5%-os sáv adója</dt><dd>{formatFt(Math.max(0,result.base-100000)*15000)}</dd></div><div><dt>Értékelési díj jóváírása</dt><dd>− {formatFt(result.feeCredit*1e6)}</dd></div><div><dt>Helyi / járműadó jóváírása</dt><dd>− {formatFt(settings.localTaxes*1e6)}</dd></div>{result.treatyCredit>0&&<div><dt>Egyezményes adólevonás</dt><dd>− {formatFt(result.treatyCredit*1e6)}</dd></div>}<div className="total"><dt>Becsült fizetendő éves adó</dt><dd data-testid={isDialog?'dialog-final-tax':'final-tax'}>{formatFt(result.rounded)}</dd></div></dl>
          {result.payable===0&&<p className="positive-note"><Check size={16}/>A megadott adatok alapján nem keletkezik fizetendő vagyonadó.</p>}
          <p className="small-note">A tervezet szerint az adó ezer forintra kerekítendő. A 100 milliárd Ft-os sávhatár a küszöb levonása utáni adóalapra vonatkozik.</p>
          <button type="button" className="button button-outline export-button" disabled={errors.length>0} onClick={exportReport}><Download size={17}/>Kalkuláció letöltése</button>
        </>}
        <div className="review-note"><Info size={18}/><p>A becslés a megadott, előzetesen meghatározott számított értékekből dolgozik. Ingatlanmodell, MNB-árfolyam, egyezmény és speciális cégértékelés nincs automatikusan lekérve. Az 500 M Ft-ot elérő, nem termőföld ingatlan külön értékelési szabályai, az illetőség és az egyedi jogviszonyok szakértői ellenőrzést igényelnek.</p></div>
  </>;
  return <section id="kalkulator" className="calculator-section section-pad"><div className="container">
    <div className="section-heading"><div><p className="eyebrow"><span/>VAGYONADÓ-KALKULÁTOR</p><h2>Ismerje meg a várható<br/><em>vagyonadó-terhét!</em></h2></div><p>A kalkulátor a jelenleg ismert szabályok alapján becslést ad. A pontos adókötelezettséghez azonban a teljes vagyoni struktúra és az egyes vagyonelemek részletes vizsgálata szükséges.</p></div>
    <div className="calculator-layout"><div className="calc-main">
      <div className="calc-steps" id="calculator-tabs" role="tablist" aria-label="Kalkulátor lépései">{steps.map((s,i)=><button key={s} id={`tab-${i}`} role="tab" aria-selected={step===i} aria-controls={`panel-${i}`} onClick={()=>move(i)} className={step===i?'active':''}><span>{step>i?<Check size={13}/>:i+1}</span>{s}</button>)}</div>
      <div className="calc-panel" id={`panel-${step}`} role="tabpanel" aria-labelledby={`tab-${step}`}>
      {step===0&&<>
        <div className="panel-title"><div><h3>Kezdjük a vagyonával.</h3><p>Összegek millió forintban, a tervezett fordulónapi értéken.</p></div><span className="tiny-pill">2026. 12. 31.</span></div>
        <div className="subject-fields"><label className="field"><span>Adóalany</span><select value={settings.subject} onChange={e=>patch({subject:e.target.value as Settings['subject']})}><option value="person">Magánszemély</option><option value="trust">Vagyonkezelési adóalany</option></select></label><label className="field"><span>Vagyonadó szerinti illetőség</span><select value={settings.resident?'hu':'foreign'} onChange={e=>patch({resident:e.target.value==='hu'})}><option value="hu">Belföldi</option><option value="foreign">Külföldi</option></select></label></div>
        <p className="scope-note"><Info size={14}/>{settings.resident?'Belföldi illetőségnél a teljes belföldi és külföldi vagyon számít.':'Külföldi illetőségnél csak a 4. § szerinti magyar ingatlan, ingatlanjog és meghatározott részesedések számítanak.'}</p>
        <details className="residence-help"><summary>Bizonytalan az illetőségében?</summary><p>A tervezet külön kivételeket ír le többek között a legalább 10 éve külföldön élő magyar állampolgárra, az 5 éves feltételek alá tartozó külföldi kiküldöttre és a meghatározott, 183 napnál kevesebbet itt tartózkodó harmadik országbeli személyre. Az illetőség nem pusztán állampolgárság vagy lakcím kérdése; a 2. § 3–4. pontja és a 34. § alapján előzetesen minősítendő.</p><button type="button" className="text-link" onClick={onContact}>Segítséget kérek az illetőség tisztázásához <ArrowUpRight size={14}/></button></details>
        <div className="asset-list">{assets.map((a,i)=><AssetEditor key={a.id} asset={a} index={i} settings={settings} onChange={next=>setAssets(assets.map(x=>x.id===a.id?next:x))} onRemove={()=>setAssets(assets.filter(x=>x.id!==a.id))}/>)}</div>
        <div className="add-asset"><button type="button" className="add-button" aria-expanded={addOpen} onClick={()=>setAddOpen(!addOpen)}><Plus size={18}/>Vagyonelem hozzáadása<ChevronDown size={16}/></button>{addOpen&&<div className="asset-menu">{assetKinds.map(k=>{const Icon=assetIcon(k.value);return <button key={k.value} type="button" onClick={()=>{setAssets([...assets,newAsset(k.value)]);setAddOpen(false);}}><Icon size={16}/>{k.label}<Plus size={14}/></button>;})}</div>}</div>
      </>}
      {step===1&&<>
        <div className="panel-title"><div><h3>A részletek is számítanak.</h3><p>Az igazolt tartozásokat és a jogosult jóváírásokat adja meg.</p></div><ShieldCheck size={25}/></div>
        <div className="deduction-block"><p className="mini-title">01 — Adóalapot csökkentő tartozás</p><Money label="Igazolt, levonható tartozások" value={settings.debt} onChange={debt=>patch({debt})} hint="Csak a 6. § szerinti, fordulónapon fennálló és igazolt tartozás. A jelen kalkulációban becsült vagyonadó nem tartozás."/><Toggle label="A tartozás megfelel a tervezet igazolási és levonhatósági feltételeinek" checked={settings.debtConfirmed} onChange={debtConfirmed=>patch({debtConfirmed})} hint={settings.resident?'Jogszabály, jogerős / végleges határozat, vagy megfelelő okiratba foglalt hitel- / kölcsönszerződés alapján.':'Külföldi illetőségnél ezen felül közvetlenül az adóköteles vagyonelemhez kapcsolódik.'}/>{settings.debt>0&&!settings.debtConfirmed&&<p className="inline-warning">Megerősítés nélkül a tartozást nem vonjuk le.</p>}</div>
        <div className="deduction-block"><p className="mini-title">02 — Fizetendő adót csökkentő tételek</p><Money label="Megfizetett helyi és gépjárműadók" value={settings.localTaxes} onChange={localTaxes=>patch({localTaxes})} hint="Csak az adóalapba bevont vagyonelemre jutó, az érintett adóévben esedékes és megfizetett adó, ideértve a megfelelő külföldi adót; visszajáró összeg nélkül. 9. § (2) b)."/><Money label="Kötelező értékelői / cégértékelési díj" value={settings.mandatoryFees} onChange={mandatoryFees=>patch({mandatoryFees})} hint="Ténylegesen megfizetett, számlával igazolt, Önt terhelő bruttó díj. 50% jóváírás, legfeljebb 2 M Ft évente."/><Toggle label="Az értékelést a törvény kötelezően előírja" checked={settings.feesConfirmed} onChange={feesConfirmed=>patch({feesConfirmed})} hint="Az önként megrendelt értékelés díja ezen a jogcímen nem vonható le."/>{settings.mandatoryFees>0&&!settings.feesConfirmed&&<p className="inline-warning">A kötelező igénybevétel megerősítéséig a díjból nincs jóváírás.</p>}</div>
        {settings.subject==='trust'&&<div className="deduction-block"><p className="mini-title">03 — Kapcsolt vagyonkezelések</p><Toggle label="Kapcsolt vagyonkezelési adóalany" checked={settings.linkedTrusts} onChange={linkedTrusts=>patch({linkedTrusts})}/>{settings.linkedTrusts&&<Money label="Ehhez az adóalanyhoz rendelt küszöb" value={settings.threshold} onChange={threshold=>patch({threshold})} hint="0–1 000 M Ft. A kapcsolt konstrukciók összesen 1 000 M Ft-ot használhatnak; az azonos tartalmú nyilatkozat vagy a 24. § (6) szerinti sorrend alapján meghatározott keretet adja meg. A számítás egy adóalanyra vonatkozik."/>}</div>}
      </>}
      {step===2&&renderResult()}
      {errors.length>0&&<div className="validation-errors" role="alert"><strong>Ellenőrizze a megadott adatokat:</strong>{errors.map((e,i)=><p key={i}>{e}</p>)}</div>}
      <div className="panel-actions"><button type="button" className="reset-button" onClick={()=>setResetOpen(true)}><RotateCcw size={14}/>Újrakezdés</button>{step<2?<button type="button" className="button button-dark" disabled={errors.length>0} onClick={()=>move(step+1)}>{step===0?'Levonások megadása':'Eredmény megtekintése'}<ArrowRight size={16}/></button>:<button type="button" className="text-link" onClick={()=>move(0)}>Adatok módosítása <ArrowRight size={16}/></button>}</div>
      {resetOpen&&<div className="reset-confirm" role="alert"><p>Törli az itt megadott vagyonelemeket és levonásokat?</p><button className="button button-dark" onClick={()=>{setAssets([newAsset()]);setSettings({...defaultSettings});setStep(0);setResetOpen(false);}}>Igen, újrakezdem</button><button className="button button-outline" onClick={()=>setResetOpen(false)}>Mégse</button></div>}
      </div><p className="privacy-note"><ShieldCheck size={15}/>A vagyoni adatok a böngészőben maradnak. Nem tároljuk és nem továbbítjuk őket.</p>
    </div>
    <aside className="result-sidebar"><div className="live-result"><div className="summary-top"><span>AZ ÖN BECSÜLT VAGYONADÓJA</span><span className="live-dot"/></div><p className="summary-label">Becsült éves fizetendő adó</p><div className="summary-value" aria-live="polite" data-testid="live-tax">{errors.length?'Ellenőrizze az adatokat':hasValue?formatFt(result.rounded):'— Ft'}</div><p className="summary-caption">A feltöltött 2026-os tervezet szerint</p><div className="summary-divider"/><dl><div><dt>Nettó vagyon</dt><dd>{errors.length?'—':formatMillion(result.net)}</dd></div><div><dt>Adómentes küszöb</dt><dd>{formatMillion(result.threshold)}</dd></div><div className="summary-base"><dt>Adóalap</dt><dd>{errors.length?'—':formatMillion(result.base)}</dd></div></dl><div className="tax-scale"><span className={result.base>0?'filled':''}/><span className={result.base>100000?'filled':''}/><span/></div><div className="scale-labels"><span>1%-os sáv</span><span>1,5%-os sáv</span></div><p className="summary-footnote">A jóváírásokkal csökkentve, ezer forintra kerekítve. Tájékoztató becslés.</p><button type="button" className="button button-light" onClick={()=>setDetailsOpen(true)} aria-haspopup="dialog">Részletes eredmény <ArrowRight size={16}/></button></div>
      <div className="expert-card"><span className="expert-icon"><CircleHelp size={22}/></span><h4>A vagyon több,<br/>mint egy szám.</h4><p>Értse meg a lehetőségeit, és tervezzen szakértővel.</p><button type="button" className="text-link" onClick={onContact}>Szakértői segítséget kérek <ArrowUpRight size={16}/></button></div>
    </aside></div>
  </div>
    <dialog ref={resultDialog} className="result-dialog" aria-labelledby="result-dialog-title" onCancel={()=>setDetailsOpen(false)} onClose={()=>setDetailsOpen(false)} onClick={e=>{if(e.target===resultDialog.current)setDetailsOpen(false);}}>
      <div className="result-dialog-toolbar"><span>ICT EURÓPA · VAGYONADÓ-KALKULÁCIÓ</span><button type="button" className="icon-button" aria-label="Részletes eredmény bezárása" onClick={()=>setDetailsOpen(false)}><X size={22}/></button></div>
      <div className="result-dialog-content">{renderResult(true)}</div>
    </dialog>
  </section>;
}
