// A felhasználó által megadott ICT Európa-tájékoztató.
export const newsletterPrivacyParagraphs: string[] = [
  "Jelen Tájékoztató célja, hogy részletes tájékoztatót nyújtson Társaságunk adatvédelmi és adatkezelési politikájáról, valamint a GDPR rendeletnek való megfeleléséről.",
  "A www.icteuropa.hu oldalon található vállalkozások egymással szorosan együttműködve jelennek meg a honlapon. A honlap üzemeltetője az ICT Európa Finance Zrt. A honlapon az együttműködő, vagy a kapcsolt vállalkozások Adatkezelési Tájékoztatói is megjelennek. Minden a honlapon megjelenő vállalat önálló, egymástól elkülönülő jogi személy. A szolgáltatásokat az egyes önálló jogi személyek nyújtják, amelyek különálló és független jogi személyek.",
  "Jelen tájékoztatás kiadója, mint a honlap üzemeltetője:",
  "ICT Európa Finance Zrt.",
  "székhely: 1117 Budapest, Budafoki út 91-93.",
  "cégjegyzékszám: 01 10 140439",
  "adószám: 27035878-2-43",
  "honlap (és a vonatkozó tényleges adatkezelések webhelye): icteuropa.hu",
  "telefonszám: +36 1 33 44 279 / fax: +36 1 29 90 474",
  "e-mail: info@icteuropa.hu",
  "önállóan képviseletre jogosultak: Lovász György vezérigazgató, Csomós István cégvezető",
  "(a továbbiakban: Társaság, Adatkezelő)",
  "1. Társaságunk általános adatfeldolgozási szerződési feltételei itt tölthető le.",
  "2. Társaságunknál alkalmazott GDPR intézkedések",
  "Társaságunk által folytatott adatkezelési, illetve adatfeldolgozási tevékenységeket a GDPR rendelkezéseknek (EURÓPAI PARLAMENT ÉS A TANÁCS (EU) 2016/679 RENDELETE, a továbbiakban: Rendelet) megfelelően szabályozzuk.",
  "Az adatkezelési és adatfeldolgozási tevékenységeinkkel összefüggésben minden munkavállalónkra kötelező érvényű belső szabályzatokkal rendelkezünk az alábbiak szerint:",
  "belső felhasználású Adatvédelmi Szabályzat",
  "nyilvánosan elérhető Adatvédelmi Tájékoztató",
  "információbiztonsági előírások",
  "adatvédelmi incidensek kezelésével kapcsolatos eljárásrend",
  "adatkezelési nyilvántartás vezetése",
  "Minden munkavállalónk számára GDPR felkészítő oktatást tartunk a személyes adatok kezelésével, feldolgozásával kapcsolatban.",
  "Informatikai rendszerünk védettségét folyamatosan fejlesztjük, hogy a munkavállalóink, Partner cégeink adatai a lehető legnagyobb biztonságban legyenek Társaságunknál.",
  "3. Társaságunk adatkezelői tevékenysége",
  "Társaság a saját munkavállalóinak foglalkoztatása, illetve bizonyos esetekben a szerződéses partnereinek nyújtott szolgáltatás során a kezelt személyes adatok vonatkozásában Adatkezelőnek minősül.",
  "4. Társaságunk adatfeldolgozói tevékenysége",
  "A Társaság szolgáltatásaival kapcsolatos szerződések kiegészítéseként minden Ügyfelünkkel adatfeldolgozási tevékenységre vonatkozó megállapodást kötünk, melyben részletesen tájékoztatjuk Partnereinket a személyes adatok kezelésével, feldolgozásával kapcsolatos eljárásokról, folyamatokról, Társaságunk jogszabályi kötelezettségeiről.",
  "A Rendelet és az egyéb hatályos jogszabályi rendelkezéseknek megfelelően csak a Megbízó előzetes és részletes tájékoztatásával és hozzájárulásával vonunk be a szolgáltatás nyújtásához további al-adatfeldolgozót. Az így bevont további al-adatfeldolgozókra ugyanazon előírások és kötelezettségek vonatkoznak a személyes adatok kezelése kapcsán, mint Társaságunkra; az al-adatfeldolgozók tevékenységéréért és az előírások betartásáért Társaságunk teljes körű felelősséget vállal, melynek részleteit minden al-adatfeldolgozóval külön szerződésben rögzíti Társaságunk.",
  "Adatfeldolgozási tevékenységünk során minden esetben a Megbízóval szerződésben rögzített megállapodásunknak megfelelően járunk el; a Megbízó által átadott adatokat saját célra, és a jogszabályokban, valamint a szerződésben meghatározottaktól eltérően nem használjuk fel. A szolgáltatás nyújtásához szükséges adatbekérést a Rendeletben előírt részletes Tájékoztatás előzi meg; csak a szerződésben meghatározott célok érdekében szükséges adatot kérjük be Megbízótól, az adatokat az adatbiztonsági előírásoknak megfelelően tároljuk, és Társaság csak azon munkavállalói férhetnek hozzá, akik a szolgáltatás nyújtásában aktívan részt vesznek. A részünkre megadott adatokat harmadik félnek nem továbbítjuk.",
  "Harmadik országba nem továbbítunk személyes adatot, kivéve, ha azt Megbízó előzetesen jóváhagyta.",
  "A Megbízó által átadott adatokat csak a szerződés teljesítéséhez szükséges ideig, illetve egyéb jogszabályi előírási kötelezettségünkig tároljuk. Az adatok törlését minden esetben úgy végezzük el, hogy az adatokat véglegesen eltávolítjuk az általunk használt valamennyi adatbázisból, és gondoskodunk azok visszaállíthatatlanságáról.",
  "Adatfeldolgozási tevékenységünkről nyilvántartást vezetünk, minden egyes adatkezelési cél tekintetében nyilvántartjuk az adatfeldolgozásra vonatkozó lényeges feltételeket, amely nyilvántartást a megbízó kérésére (az általa folytatott adatkezelésekre vonatkozóan) átadunk.",
  "5. Adatbiztonsági intézkedések",
  "Társaságunk az általunk kezelt és szerződött Partnereink részéről átadott adatok biztonságos tárolása érdekében információbiztonsági szabályzattal rendelkezik. Az adatbiztonsági intézkedések tekintetében minden olyan lépést megteszünk, ami az általunk tárolt személyes adatok védelmét biztosítja. Megtesszük és folyamatosan fejlesztjük azokat a technikai és szervezési intézkedéseket, melyekkel az általunk tárolt és feldolgozott adatokat megvédjük a jogosulatlan hozzáférés, adatszivárgás, adatvesztés, nyilvánosságra hozás, megsemmisítés ellen. Valamint kialakításra kerültek azok a belső eljárási szabályok, amelyek az adatvédelmi és titoktartási kötelezettségünk folyamatos teljesítéséhez szükségesek.",
  "6. Panaszkezelés, adatvédelemi incidens",
  "Amennyiben Társaságunkhoz egy érintett részéről bármilyen panasz vagy kérés érkezne személyes adatai kezelésével, feldolgozásával, valamint törvényes jogai gyakorlásával kapcsolatban, a kérést azonnal kivizsgáljuk, és amennyiben szükséges, jelezzük azt a felügyeleti szerv (NAIH) felé.",
  "Társaságunk egy esetleges adatvédelmi incidens bekövetkezésének esetére incidenskezelési eljárásrendet készített, melynek részleteit a Társaság Adatvédelmi Szabályzata tartalmazza. Az adatvédelmi incidensekről nyilvántartást vezetünk. Minden esetben, amikor adatvédelmi incidenst észlelünk, megvizsgáljuk annak részleteit, felmérjük a kockázatát és megtesszük a szükséges korrekciós intézkedéseket a nagyobb probléma mérséklése érdekében. Haladéktalanul értesítjük a Megbízót az incidens bekövetkeztéről, és amennyiben az incidens mértéke és esetleges következménye indokolja 72 órán belül értesítjük a felügyeleti hatóságot (NAIH) is.",
  "Érintett bármilyen adatkezeléssel kapcsolatos kérdésével, panaszával, észrevételével kapcsolatban az alábbi elérhetőség valamelyikén megkeresheti Társaságunkat:",
  "E-mail: info@icteuropa.hu",
  "Tel.: (+36) 1 33 44 279",
  "ICT Európa Holding Zrt."
];
